name: IamAuth
version: '${project.version}'
main: com.dig.iamauth.Main
commands:
  register:
  login:
  changepassword:
    aliases:
      - changepass
  unregister:
  auth:
    aliases:
      - iamauth
